{% set version = "0.50-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clustersim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clusterSim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clusterSim/clusterSim_{{ version }}.tar.gz
  sha256: 8a91671775362d51460e539d146ebd43b50be26edaa2fd2ed5bf259a70b89738

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ade4
    - r-cluster
    - r-e1071
    - r-mass
    - r-r2html
    - r-rgl
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ade4
    - r-cluster
    - r-e1071
    - r-mass
    - r-r2html
    - r-rgl

test:
  commands:
    - $R -e "library('clusterSim')"           # [not win]
    - "\"%R%\" -e \"library('clusterSim')\""  # [win]

about:
  home: http://keii.ue.wroc.pl/clusterSim
  license: GPL-2.0-or-later
  summary: "Distance measures (GDM1, GDM2,\tSokal-Michener, Bray-Curtis, for symbolic interval-valued data), cluster quality indices (Calinski-Harabasz, Baker-Hubert, Hubert-Levine, Silhouette, Krzanowski-Lai, Hartigan, Gap,\tDavies-Bouldin),\tdata normalization formulas (metric data, interval-valued symbolic data), data\
    \ generation (typical and non-typical data), HINoV method,\treplication analysis, linear ordering methods, spectral clustering, agreement indices between two partitions, plot functions (for categorical and symbolic interval-valued data).  (MILLIGAN, G.W., COOPER, M.C. (1985) <doi:10.1007/BF02294245>,  HUBERT, L., ARABIE,\
    \ P. (1985) <doi:10.1007%2FBF01908075>,  RAND, W.M. (1971) <doi:10.1080/01621459.1971.10482356>,  JAJUGA, K., WALESIAK, M. (2000) <doi:10.1007/978-3-642-57280-7_11>,  MILLIGAN, G.W., COOPER, M.C. (1988) <doi:10.1007/BF01897163>,  JAJUGA, K., WALESIAK, M., BAK, A. (2003) <doi:10.1007/978-3-642-55721-7_12>,  DAVIES, D.L.,\
    \ BOULDIN, D.W. (1979) <doi:10.1109/TPAMI.1979.4766909>,  CALINSKI, T., HARABASZ, J. (1974) <doi:10.1080/03610927408827101>, HUBERT, L. (1974) <doi:10.1080/01621459.1974.10480191>,  TIBSHIRANI, R., WALTHER, G., HASTIE, T. (2001) <doi:10.1111/1467-9868.00293>,  BRECKENRIDGE, J.N. (2000) <doi:10.1207/S15327906MBR3502_5>,\
    \  WALESIAK, M., DUDEK, A. (2008) <doi:10.1007/978-3-540-78246-9_11>)."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
