appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: S2hDS09nAE5/fSZ92sq5AsR1Vp4ED1RSSxmz5cAy6RSekIO6Zw7V7DaK8IsSRxGwDfr+sEqAD+lDl/25viqB2q2JHWndHCXg46nqR0wDMW0Ejn275Heo5fz6q+t6slKLl6nIXYiY6cnwj3LDLCDD6AU7ShY4464vWK0xaDjZ49Q0gj1gH/4ljT+sdnOcYDDU6cjdgHhQ1lmwbBiZ63nKVZYRiJKCT/KTdqzcVEy/lMkqdcFP51r2UzHZanAqTJ0T+/7z9G9IpcHtLcXc7kHCHo+lL9BAI3ufqr0JxkTbv7wtL/9ZIz1c6qhLQByG40j8ec/Zs9VouqJSr335aqr/3MmT6nxfduj/Hl+/zT/YpB1knl0aKzSZY5DdZ1EV7olEumXygTQ2xGpim+ZpR6Wns8us05trF2Nykb8CXoso2Q1z5xz7CJD72BlyG4GTCjuqIHuw7jrXGLETRTfQi6C1G31Ce2uAqZxYSUefxAseRN8+Ss2mcibKjatLZBLt79mPxq6SLWgPAXgx4lru8jLQah8aGECFZ+wAxsO+H+5hazOSHyvS7RCsmGm32X+4q/Xd1y0dvoPLihRQb2+DYNJRKUe35fEG5HEvsbKRSO9YoQGvlryTF3N3fx6k+jJDqaC4g66YNJw/TjQ/8zDmHgXemyZy/UvwLHoW66tAVSYMYzU=
